baseURL: /
title: Andy Zheng
theme: hugo-theme-bootstrap
copyright: 'Copyright ©{year}, All Rights Reserved.'
defaultContentLanguage: zh-hans
hasCJKLanguage: true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.
# defaultContentLanguageInSubdir: true
# disableLanguages:
#  - en
paginate: 10
# paginatePath: page
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45
# disqusShortname: yourdiscussshortname

blackfriday:
  hrefTargetBlank: true

taxonomies:
  category: categories
  # series: series
  tag: tags
  # authors: authors

build:
  writeStats: true

permalinks:
  blog: /blog/:year/:month/:filename/

# module:
  # proxy: https://goproxy.cn
